### ISSUE TITLE
Enhencement: Install Instruction for Linux

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [disks86/VK9#42]
The wiki provides an install instruction for Windows correct?

Is it possible to add install instruction for Linux based on the "Release" builds?

**Comment by disks86** [comment]
I think there are some details to help in the Linux build instructions but I don't believe separate install instructions were provided in the PR. I think there is just a script to run to install.

**Comment by RicardoEPRodrigues** [comment]
I need to build VK9 to use it on Linux?

Can't I just use the "Release" builds?

Forgive my lack of knowledge. :smile:

**Comment by baka0815** [comment]
It should be enough to just copy those files from the zip into the directory of the game or the Windows directory of your wine home.

**Comment by RicardoEPRodrigues** [comment]
When I can I'll try to run Guild Wars 2 using VK9.

How can I check if the VK9 is being used? DXVK is using log files (`d3d11.log` and `dxgi.log`) or using a HUD.

**Comment by Zeioth** [comment]
For GW2 you need the x64 bits version of vk9. Right now you must compile it by yourself. But if you can't, wait. In the next releases it is gonna be avaliable too, I think.

**Comment by PadreAdamo** [comment]
Hell yes! GW2 is the driving force for me as well. I am not a developer but
contribute where I can which happens to be the Patreon. Please let me know
if AI could assist with testing. I have an all AMD machine.

**Comment by disks86** [comment]
@RicardoEPRodrigues VK9 creates a VK9.log file when it runs.

**Comment by RicardoEPRodrigues** [comment]
I think I'll wait for a next x64 build in "Release" and then try it out.

I don't currently have a machine with the needed dependencies.

Thank you!

**Comment by mmmaisel** [comment]
New 32bit and 64bit releases are out now.

On Linux, VK9 dlls have to copied into
- 32bit WINEPREFIX, 32bit dll: $WINEPREFIX/drive_c/windows/system32
- 64bit WINEPREFIX, 32bit dll: $WINEPREFIX/drive_c/windows/syswow64
- 64bit WINEPREFIX, 64bit dll: $WINEPREFIX/drive_c/windows/system32

and d3d9.dll has to be set to "native" in winecfg.

All compiled shaders (*.spv) and VK9.conf have to be copied to the directory of the exe file.

**Comment by RicardoEPRodrigues** [comment]
This info should be added to the [Installation Instructions](https://github.com/disks86/VK9/wiki/Installation-Instructions)! :smile:

**Comment by RicardoEPRodrigues** [comment]
One question: Should I place the `D3d9.pdb` file next to the `.dll` file? Can it be ignored?

**Comment by RicardoEPRodrigues** [comment]
Ok. At this moment I can't get it to work, but let me describe what I've done.

First of all I downloaded GW2, I used a portable GW2/Wine version from the [GW2 Forums](https://en-forum.guildwars2.com/discussion/31192/playing-guild-wars-2-on-linux-performance-optimizations-and-more).

If offers a couple of simple commands, `play`, `setup` and `wine_settings`, the last one opens up the wine config for the bundled Wine prefix.

With this base what I did was follow the previously mentioned instructions, using 64bit WINEPREFIX:

1. Copied 64bit dll: $WINEPREFIX/drive_c/windows/system32 (renamed from D3d9 to d3d9)
1. Copied 32bit dll: $WINEPREFIX/drive_c/windows/syswow64 (renamed from D3d9 to d3d9)
1. Ran `wine_settings.sh` to open winecfg. Then `Libraries > New override > d3d9 > set Native`.
1. Ran `play.sh` to start GW2... CRASH! (See crash log from game bellow).
1. Notice that `vulkan.dll` is referenced, so I believe it is related with the d3d9 being loaded.
1. Modified d3d9 to `Native then Builtin`. Works but does not use VK9.

[crashlog.txt](https://github.com/disks86/VK9/files/2040925/crashlog.txt)

Can you help out? If you want me to test something just say it :smile:

**Comment by Zeioth** [comment]
@RicardoEPRodrigues I can reproduce your error.

[cashlog.log](https://github.com/disks86/VK9/files/2041163/cashlog.log)

And I can't find VK9.log either, even after changing VK9.conf path to 

    LogFile = /home/zeioth/vk9.log

**Comment by PadreAdamo** [comment]
Is anyone using this guild wars 2 without issue?

**Comment by Zeioth** [comment]
@PadreAdamo Don't expect VK9 to be fully functional yet. We are just trying to provide useful information to @disks86 .

**Comment by RicardoEPRodrigues** [comment]
Unfortunately the crash log is not very informative I believe.

I posted an issue on the portable GW2/Wine for the Wine version to be ported to 3.x ([link](https://github.com/Jrugia/wine_gw2/issues/1)), this way maybe we can have a place to easily test the VK9 on GW2.

**Comment by mmmaisel** [comment]
@disks86 
I attached [installation instructions](https://github.com/disks86/VK9/files/2045518/Installation-Instructions.md.txt) for Linux to this comment. Please merge them to the wiki.

**Comment by disks86** [comment]
@mmmaisel Thank you, I merged these into the wiki.

**Comment by RicardoEPRodrigues** [comment]
@disks86 Regarding GW2/Wine portable, they updated the Wine version.

https://github.com/Jrugia/wine_gw2/issues/1#issuecomment-394495508

This might be a better version to test on, although it still crashes :smile: 

If you want to test things out it's a good base point.

**Comment by Pillgar** [comment]
I had a similar experience with Star Wars: The Old Republic.  The game would crash upon executing the launcher when d3d9 was set to native.  Setting it to "native then builtin" worked, though there was no VK9.log, thus indicating it wasn't being used.  I noticed there is a D3d9.pdb file with no mention of it in the instructions.  Should that be copied to system32/syswow64 or the .exe directory?

**Comment by RicardoEPRodrigues** [comment]
@Pillgar I believe the `.pdb` file is for debug purposes, so it can be ignored 😄

**Comment by DxCx** [comment]
Hey @RicardoEPRodrigues
Any luck with gw2?
Im playing with wine pba atm but results still not sufficient :/

**Comment by RicardoEPRodrigues** [comment]
@DxCx I believe VK9 still hasn't implemented all needed features for GW2 to work.

For now I'm waiting and watching out for VK9 development and also [D3D9 to 11](https://github.com/GabrielMajeri/d3d9-to-11).

**Comment by DxCx** [comment]
@RicardoEPRodrigues  let me know if you are able to get something working please (i'll do the same ofc)
i am getting around 20fps using Nvidia 1050 (i7 7700HQ) this is just feels wrong... :|
